from tkinter import *


def scrum(foablak):
    k1 = BooleanVar()
    k2 = BooleanVar()
    k3 = BooleanVar()
    k4 = BooleanVar()
    k5 = BooleanVar()
    scrum_ablak = Toplevel(foablak, width=600, height=400)
    scrum_ablak.minsize(width=600, height=400)
    scrum_ablak.title("Scrum teszt")
    kerdes1 = Label(text="Hány szerepkör van a scrum-ban?")
    kerdes2 = Label(text="Van-e főnökük a fejlesztőknek?")
    kerdes3 = Label(text="Rugalmas a scrum?")
    kerdes4 = Label(text="Hány dokumentum van a scrum-ban?")
    kerdes5 = Label(text="Hány esemény van a scrumban?")
    valaszgomb1_1 = Radiobutton(scrum_ablak, text="5",variable=k1, value=False)
    valaszgomb1_2 = Radiobutton(scrum_ablak, text="3",variable=k1, value=True)
    valaszgomb1_3 = Radiobutton(scrum_ablak, text="4",variable=k1, value=False)
    valaszgomb2_1 = Radiobutton(scrum_ablak, text="Nincs",variable=k2, value=True)
    valaszgomb2_2 = Radiobutton(scrum_ablak, text="Van",variable=k2, value=False)
    valaszgomb2_3 = Radiobutton(scrum_ablak, text="Totya a főnök",variable=k2, value=False)
    valaszgomb3_1 = Radiobutton(scrum_ablak, text="Igen",variable=k3, value=True)
    valaszgomb3_2 = Radiobutton(scrum_ablak, text="Nem",variable=k3, value=False)
    valaszgomb3_3 = Radiobutton(scrum_ablak, text="Félig",variable=k3, value=False)
    valaszgomb4_1 = Radiobutton(scrum_ablak, text="4",variable=k4, value=False)
    valaszgomb4_2 = Radiobutton(scrum_ablak, text="3",variable=k4, value=True)
    valaszgomb4_3 = Radiobutton(scrum_ablak, text="6",variable=k4, value=False)
    valaszgomb5_1 = Radiobutton(scrum_ablak, text="3",variable=k5, value=False)
    valaszgomb5_2 = Radiobutton(scrum_ablak, text="7",variable=k5, value=False)
    valaszgomb5_3 = Radiobutton(scrum_ablak, text="5",variable=k5, value=True)

    kerdes1.place(relx=, rely=, anchor=)
    kerdes2.place(relx=, rely=, anchor=)
    kerdes3.place(relx=, rely=, anchor=)
    kerdes4.place(relx=, rely=, anchor=)
    kerdes5.place(relx=, rely=, anchor=)
    valaszgomb1_1.place(relx=, rely=, anchor=)
    valaszgomb1_2.place(relx=, rely=, anchor=)
    valaszgomb1_3.place(relx=, rely=, anchor=)
    valaszgomb2_1.place(relx=, rely=, anchor=)
    valaszgomb2_2.place(relx=, rely=, anchor=)
    valaszgomb2_3.place(relx=, rely=, anchor=)
    valaszgomb3_1.place(relx=, rely=, anchor=)
    valaszgomb3_2.place(relx=, rely=, anchor=)
    valaszgomb3_3.place(relx=, rely=, anchor=)
    valaszgomb4_1.place(relx=, rely=, anchor=)
    valaszgomb4_2.place(relx=, rely=, anchor=)
    valaszgomb4_3.place(relx=, rely=, anchor=)
    valaszgomb5_1.place(relx=, rely=, anchor=)
    valaszgomb5_2.place(relx=, rely=, anchor=)
    valaszgomb5_3.place(relx=, rely=, anchor=)


    
    scrum_ablak.mainloop()